#
# Makefile for the Linux unix domain socket layer.
#

obj-$(CONFIG_CAMEO)	+= cameo.o

cameo-$(CONFIG_CAMEO_CT_NEW)	+= cameo_ct.o
cameo-$(CONFIG_CAMEO_TP_NEW)	+= cameo_tp.o
cameo-$(CONFIG_CAMEO_LOG_PKT)	+= cameo_log_pkt.o
cameo-$(CONFIG_CAMEO_KLOG_ENTRY)	+= cameo_klog_entry.o
